### ISSUE TITLE
Using 'False

### ISSUE THREAD

**Issue by JMBradTillman** [lorenh/xmlpreprocess#1]
I've found that using False to undefine settings does not work. It looks like in the code the FixFalse flag is always set to true due to the use of the compilation symbol 'NOFIXFALSE' not being defined in CommandLine.cs:90.

**Comment by JMBradTillman** [comment]
I've found that using False to undefine settings does not work. It looks like in the code the FixFalse flag is always set to true due to the use of the compilation symbol 'NOFIXFALSE' not being defined in CommandLine.cs:90.

**Comment by lorenh** [comment]
That is an obsolete setting, and there should be no need for it at all.  Undefining settings is now done by setting a value of "#undef"

I still have to bring over the documentation from Codeplex, but for now you can still look through it there.

http://xmlpreprocess.codeplex.com/wikipage?title=Properties

**Comment by JMBradTillman** [comment]
That's too bad. I thought it was a new feature. Just curious, is there a reason for using #undef  instead of 'False'?

**Comment by lorenh** [comment]
Yep, There are many many times where you want "False" to be the value of the setting, leaving an ambiguity for the preprocessor (Did he mean "false", or did he mean to undefine the property?).  False was a mistake from the very early days of XmlPreprocess and now hopefully the mistake is behind for good.  The command line switch was left in so existing scripts didn't break, but it really should be removed too.  Here's an example.  You don't want to undefine the setting, you want the setting to render "False" into the output file.  

    
    
    
    <compilation targetFramework="4.5.2" debug="true">
    

"#undef" was chosen as a magic string just to undefine properties that is unlikely to conflict with anyone's values.
