### ISSUE TITLE
BizTalk BTDF Deployment: Placeholders are not replaced with values from settings file

### ISSUE THREAD

**Issue by suryasreepada** [lorenh/xmlpreprocess#2]
The output file is generated with placeholders (same as input file)
Values from settings file are not replaced using below command.

BTDF Version: 5.7
BizTalk Server 2013
OS: Windows 10 Pro 64-Bit
VS: Visual Studio 2013 Professional

This command is executed from below option in Visual Studio.
Tools -> Deployment Framework for BizTalk -> Deploy BizTalk Solution

Command:
"C:\Program Files (x86)\XXX\1.0.0\Deployment\Framework\DeployTools\xmlpreprocess.exe" /v /c /noDirectives /i:"D:\Program Files (x86)\XXX\1.0.0\Deployment\Input.xml" /o:"C:\Program Files (x86)\XXX\1.0.0\Deployment\Output.xml" /d:CurDir="C:\Program Files (x86)\XXX\1.0.0" /s:"C:\Program Files (x86)\XXX\1.0.0\Deployment\EnvironmentSettings\Settings.xml"

XML content in the input file is minimized to keep it simple.
In actual scenario, the input file contains actual BindingInfo for a BizTalk Application.

Input.xml:
&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;mysettings&gt;
  &lt;property&gt;${Test1}&lt;/property&gt;
  &lt;property&gt;${Test2}&lt;/property&gt;
&lt;/mysettings&gt;

Settings.xml:
&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;settings&gt;
  &lt;property name="Test1"&gt;Test_1_Value&lt;/property&gt;
  &lt;property name="Test2"&gt;Test_2_Value&lt;/property&gt;
&lt;/settings&gt;

Generated xml:
&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;mysettings&gt;
  &lt;property&gt;${Test1}&lt;/property&gt;
  &lt;property&gt;${Test2}&lt;/property&gt;
&lt;/mysettings&gt;

Due to this problem, we are not able to use the BTDF Deployment in Local Machine.
Could someone please check this and validate that this error is consistent in other environments?

**Comment by lorenh** [comment]
The input file typically contains preprocessing ifdefs like this:

```
<?xml version="1.0" encoding="utf-8"?>
<mysettings>
<!-- #ifdef _xml_preprocess -->
<!--
<property>${Test1}</property>
<property>${Test2}</property>
-->
<!-- #endif -->
</mysettings>
```


Alternately you could use the /noDirectives switch to just treat the input file as plain text.

**Comment by suryasreepada** [comment]
Using below property in BTDF Project file fixed our issue.

&lt;PropertyGroup Condition="'$(Configuration)' != 'Server'"&gt;
    &lt;RequireXmlPreprocessDirectives&gt;False&lt;/RequireXmlPreprocessDirectives&gt;
&lt;/PropertyGroup&gt;

Thanks for the help.
